{{- $blobberCount := .Values.blobber.blobberCount | int }}
{{- $blobberCount := add $blobberCount 1 | int }}
{{- range $i := untilStep 1 $blobberCount 1 }}
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    {{- include "0helm-blobber.labels" $ | nindent 6 }}-postgres-post-0{{ $i }}
  name: {{ include "0helm-blobber.fullname" $ | nindent 4 }}-postgres-post-0{{ $i }}
spec:
  template:
    spec:
      containers:
        - name: {{ $.Release.Name }}-postgres
          image: {{ $.Values.blobber.postgresImage.repository }}:{{ $.Values.blobber.postgresImage.tag }}
          resources:
            {{- toYaml $.Values.blobber.postgresResources | nindent 12 }}
          args:
            - bash
            - /blobber/bin/postgres-entrypoint.sh
          env:
            {{- range $key, $value := $.Values.blobber.postgresJobEnv }}
            - name: {{ $key }}
              value: {{ $value | quote }}        
            {{- end }}
            - name: POSTGRES_HOST
              value: {{ include "0helm-blobber.fullname" $ | nindent 15 }}-postgres-0{{ $i }}
          volumeMounts:
            - mountPath: /blobber/bin
              name: postgres-bin-pvc
            - mountPath: /blobber/sql
              name: postgres-sql-pvc
      restartPolicy: Never
      volumes:
        - name: postgres-sql-pvc
          configMap:
            name: blobber-sql
            defaultMode: 0755
        - name: postgres-bin-pvc
          configMap:
            name: blobber-bin
            defaultMode: 0755

{{- end }}