apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "0helm.labels" $ | nindent 4 }}-minio-config-blobber
  creationTimestamp: null
  name: minio-config-blobber
stringData:
  minio_config.txt: |-
    {{- $.Values.blobber.minioConfig.bucketUrl | nindent 4 }}
    {{- $.Values.blobber.minioConfig.accessKeyId | nindent 4 }}
    {{- $.Values.blobber.minioConfig.secretAccessKey | nindent 4 }}
    {{- $.Values.blobber.minioConfig.bucketName | nindent 4 }}
    {{- $.Values.blobber.minioConfig.bucketRegion | nindent 4 }}
