apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "0helm.labels" $ | nindent 4 }}-blobber-bin
  creationTimestamp: null
  name: blobber-bin
data:
  postgres-entrypoint.sh: "#!/bin/bash\n\nset -e\n\npsql=( psql --username \"$POSTGRES_USER\"
    --port \"$POSTGRES_PORT\" --host \"$POSTGRES_HOST\" )\n\nuntil pg_isready -h $POSTGRES_HOST\ndo\n\techo
    \"Sleep 1s and try again...\"\n\tsleep 1\ndone\n\nfor f in /blobber/sql/*; do\n\tcase
    \"$f\" in\n\t\t*.sh)     echo \"$0: running $f\"; . \"$f\" ;;\n\t\t*.sql)    echo
    \"$0: running $f\"; \"${psql[@]}\" -f \"$f\"; echo ;;\n\t\t*.sql.gz) echo \"$0:
    running $f\"; gunzip -c \"$f\" | \"${psql[@]}\"; echo ;;\n\t\t*)        echo \"$0:
    ignoring $f\" ;;\n\tesac\n\techo\ndone"
    