{{- $blobberCount := .Values.blobber.blobberCount | int }}
{{- $blobberCount := add $blobberCount 1 | int }}
{{- range $i := untilStep 1 $blobberCount 1 }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "0helm-blobber.labels" $ | nindent 4 }}-blobber-0{{ $i }}
  name: {{ include "0helm-blobber.fullname" $ | nindent 4 }}-blobbergrpc-0{{ $i }}
spec:
  ports:
    - name: "{{ $.Values.blobber.blobberGrpcService.port }}{{ $i }}"
      port: {{ $.Values.blobber.blobberGrpcService.port }}{{ $i }}
      nodePort: {{ $.Values.blobber.blobberGrpcService.nodePort }}{{ $i }}
      targetPort: {{ $.Values.blobber.blobberGrpcService.port }}{{ $i }}
  type: {{ $.Values.blobber.blobberGrpcService.type }}
  selector:
    {{- include "0helm-blobber.selectorLabels" $ | nindent 6 }}-blobber-0{{ $i }}

{{- end }}