{{- $blobberCount := .Values.blobber.blobberCount | int }}
{{- $blobberCount := add $blobberCount 1 | int }}
{{- range $i := untilStep 1 $blobberCount 1 }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "0helm.labels" $ | nindent 4 }}-blobber-0{{ $i }}
  name: {{ $.Chart.Name }}-blobber-0{{ $i }}
spec:
  ports:
    - name: "{{ $.Values.blobber.blobberService.port }}{{ $i }}" 
      port: {{ $.Values.blobber.blobberService.port }}{{ $i }}
      nodePort: {{ $.Values.blobber.blobberService.nodePort }}{{ $i }}
      targetPort: {{ $.Values.blobber.blobberService.port }}{{ $i }}
  type: {{ $.Values.blobber.blobberService.type }}
  selector:
    {{- include "0helm.selectorLabels" $ | nindent 6 }}-blobber-0{{ $i }}

{{- end }}