name: Dockerize_Image_Build

on:
  workflow_dispatch:
    inputs:
      latest_tag:
        description: 'type yes for building latest tag'
        default: 'no'
        required: true
jobs:
  run: |
     echo "Hello"


